services:
  web:
    image: nginx
    ports:
      - "8001:80"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
      MYSQL_USER: sreepriya
      MYSQL_PASSWORD: pass987
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8070:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  dbdata:
